<?php
// First, split it up and get the root
$subdomain = $_GET['subdomain'];
if($subdomain) {
    $subdomain_split = explode($subdomain, '-');
    $subdomain_base = $subdomain_split[0];
}

// Output a basic manifest
if(($_GET['file'] == "manifest.webapp" || $_GET['file'] == "manifest.json") && $subdomain) {
    header("Content-Type: application/x-web-app-manifest+json");

    $data = array('name'=>'Test App ('.$subdomain.')',
                  'description'=>'This app has been automatically generated by testmanifest.com');

    echo json_encode($data);
} else {
    include "words.php";
    $random = rand(1000, 9999);
    $manifest = "http://" . $animals[rand(0, count($animals))] . $random . ".testmanifest.com/manifest.webapp";
?>
<div style="text-align: center;">
    <h1>Your random manifest is&hellip;</h1>
    <input type="text" value="<?= $manifest ?>"><br>
    (Or, just use any subdomain)
</div>
<?
}
