<?php
// First, split it up and get the root
$subdomain_full = explode($_GET['subdomain'], '-');
$subdomain = $subdomain[0];

// Output a basic manifest
if($_GET['file'] == "manifest.webapp") {
    header("Content-Type: application/x-web-app-manifest+json");

    $data = array('name'=>'Test App ('.$subdomain_full.')',
                  'description'=>'This app has been automatically generated by testmanifest.com');

    echo json_encode($data);
}
