<?php
// First, split it up and get the root
$subdomain = $_GET['subdomain'];
$subdomain_split = explode($subdomain, '-');
$subdomain_base = $subdomain_split[0];

// Output a basic manifest
if($_GET['file'] == "manifest.webapp") {
    header("Content-Type: application/x-web-app-manifest+json");

    $data = array('name'=>'Test App ('.$subdomain.')',
                  'description'=>'This app has been automatically generated by testmanifest.com');

    echo json_encode($data);
}
